image:
  repository: tccr.io/truecharts/anonaddy
  tag: v0.11.1@sha256:e4312494b11c9de4437c3980841545ce6c9687afe59e24cd53cf5ae14dd44b9e
  pullPolicy: IfNotPresent

strategy:
  type: Recreate

securityContext:
  runAsNonRoot: false
  readOnlyRootFilesystem: false


podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

# -- environment variables. See more environment variables in the [anonaddy documentation](https://github.com/anonaddy/docker#environment-variables).
# @default -- See below
env:
  # -- Root domain to receive email from
  ANONADDY_DOMAIN: chart-example.local
  DB_DATABASE: anonaddy
  DB_USERNAME: Kagiso

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 10110
        targetPort: 8000
  smtp:
    enabled: true
    ports:
      smtp:
        enabled: true
        port: 25
        targetPort: 25

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  varrun:
    enabled: true
    size: 2Gi
  config:
    enabled: true
    size: 2Gi
    mountPath: "/config"

envValueFrom:
  DB_HOST:
    secretKeyRef:
      name: mysql-creds
      key: host
  DB_PASSWORD:
    secretKeyRef:
      name: mysql-creds
      key: mysql-password
  REDIS_HOST:
    secretKeyRef:
      name: rediscreds
      key: plainhost
  REDIS_PASSWORD:
    secretKeyRef:
      name: rediscreds
      key: redis-password
  APP_KEY:
    secretKeyRef:
      name: appkey
      key: appkey
  ANONADDY_SECRET:
    secretKeyRef:
      name: appkey
      key: secret


redis:
  enabled: false
  existingSecret: "rediscreds"

mariadb:
  enabled: false
  mariadbUsername: anonaddy
  mariadbDatabase: anonaddy
  existingSecret: "mariadbcreds"
