image:
  repository: tccr.io/truecharts/overseerr
  tag: 12.3.0@sha256:08d9ff12404b40eab134d9bcd11bbff939d7da44e61e5cc262fffa985ac5b848
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 5055
        targetPort: 5055
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
    size: 5Gi
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
