image:
  repository: tccr.io/truecharts/overseerr
  tag: 12.3.0@sha256:ab6e54739c41312b27f955a694203375eb06318ceebf74a502387d7a10928ecc
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 5055
        targetPort: 5055
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
    size: 5Gi
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
