image:
  repository: tccr.io/truecharts/overseerr
  tag: 12.1.6@sha256:d28c232a18f634d7fedabe66d2a849b83a166b3bae4180a71263fdd435868218
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 5055
        targetPort: 5055
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
    size: 5Gi
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
