image:
  repository: tccr.io/truecharts/overseerr
  tag: 12.1.5@sha256:08f7cfa4055238336109979784bea76f66306062424e53e8388a63e7173a46e4
  pullPolicy: IfNotPresent
service:
  main:
    ports:
      main:
        port: 5055
        targetPort: 5055
persistence:
  config:
    enabled: true
    mountPath: "/app/config"
    size: 5Gi
portal:
  open:
    enabled: true
securityContext:
  container:
    readOnlyRootFilesystem: false
workload:
  main:
    podSpec:
      containers:
        main:
          env:
            LOG_LEVEL: info
