apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  destination:
    namespace: default
  project: default
  sources:
    # Chart from Chart Repo
    - chart: nextcloud
      repoURL: https://nextcloud.github.io/helm/
      targetRevision: 4.3.1
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
        - $values/Apps/nextcloud/values.yml
    # Values from Git
    - repoURL: 'https://github.com/Kagiso-me/Kubernetes-k3s/'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true