---
image:
  repository: nextcloud
  tag: 27.1.3
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
podAnnotations: {}
deploymentAnnotations: {}
replicaCount: 1
ingress:
  enabled: false
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 4G
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/server-snippet: ""
  tls:
    - secretName: nextcloud-tls
      hosts:
        - hostname.me
  labels: {}
  path: /
  pathType: Prefix
lifecycle: {}
phpClientHttpsFix:
  enabled: false
  protocol: https
nextcloud:
  host: host
  username: "user"
  password: "password"
  existingSecret:
    enabled: true
    secretName: nextcloud
    username: nextcloud-username
    password: nextcloud-password
  update: 0
  datadir: /var/www/html/data
  persistence:
    subPath: 
  mail:
    enabled: true
    fromAddress: "Kagiso.tech"
    domain: ""
    smtp:
      host: "smtp-mail.outlook.com"
      secure: ssl
      port: 465
      authtype: LOGIN
      name: ""
      password: ""
  phpConfigs: {}
  defaultConfigs:
    .htaccess: true
    redis.config.php: true
    apache-pretty-urls.config.php: true
    apcu.config.php: true
    apps.config.php: true
    autoconfig.php: true
    smtp.config.php: true
  configs:
    proxy.config.php: |-
      <?php
      $CONFIG = array (
        'trusted_proxies' => array(
          0 => '127.0.0.1',
          1 => '10.0.0.0/8',
          2 => 'kagiso.tech',
          3 => '',
        ),
        'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
      );
  strategy:
    type: Recreate
  extraEnv: null
  extraInitContainers: []
  extraSidecarContainers: []
nginx:
  enabled: false
  image:
    repository: nginx
    tag: alpine
    pullPolicy: IfNotPresent
  config:
    default: true
  resources: {}
internalDatabase:
  enabled: false
  name: "nextcloud"
externalDatabase:
  enabled: true
  type: mysql
  host: 10.0.1.10
  user: ""
  password: ""
  database: ""
  existingSecret:
    enabled: true
    secretName: nextcloud-db
    usernameKey: mariadb-username
    passwordKey: mariadb-password
mariadb:
  enabled: false
  auth:
    database: "nextcloud"
    username: "user"
    password: "password"
  architecture: standalone
  primary:
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: 6Gi
postgresql:
  enabled: false
  global:
    postgresql:
      auth:
        username: nextcloud
        password: changeme
        database: nextcloud
  primary:
    persistence:
      enabled: false
redis:
  enabled: false
  auth:
    enabled: true
    password: changeme
cronjob:
  enabled: false
  lifecycle: {}
service:
  type: LoadBalancer
  port: 8080
  loadBalancerIP:
  nodePort: 
persistence:
  enabled: true
  annotations: {}
  storageClass: longhorn
  accessMode: ReadWriteMany
  size: 100Gi
  nextcloudData:
    enabled: false
    subPath: null
    annotations: {}
    accessMode: ReadWriteMany
    size: 8Gi
resources:
  limits:
    cpu: 620m
    memory: 850Mi
  requests:
    cpu: 360m
    memory: 500Mi
livenessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 20
  failureThreshold: 3
  successThreshold: 1
readinessProbe:
  enabled: true
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 20
  failureThreshold: 3
  successThreshold: 1
startupProbe:
  enabled: false
  initialDelaySeconds: 120
  periodSeconds: 60
  timeoutSeconds: 20
  failureThreshold: 30
  successThreshold: 1
hpa:
  enabled: false
  cputhreshold: 60
  minPods: 1
  maxPods: 10
nodeSelector: {}
tolerations: []
affinity: {}
metrics:
  enabled: false
  replicaCount: 1
  https: false
  token: ""
  timeout: 5s
  tlsSkipVerify: false
  image:
    repository: xperimental/nextcloud-exporter
    tag: 0.6.2
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9205"
    labels: {}
  serviceMonitor:
    enabled: false
    namespace: ""
    jobLabel: ""
    interval: 30s
    scrapeTimeout: ""
    labels: {}
rbac:
  enabled: false
  serviceaccount:
    create: true
    name: nextcloud-serviceaccount
    annotations: {}