image:
  repository: tccr.io/truecharts/projectsend
  pullPolicy: IfNotPresent
<<<<<<< HEAD
  tag: vlatest@sha256:e359438814bfddc801c43ef0465523e1d6a3ce4fd063c198a4a98ac2028948b4
=======
  tag: vlatest@sha256:a5bf74f8d721227bf073c6b8e96ac5163d5ef2551c488585976b65e4e36c2ccc
>>>>>>> 0fd210691f56139a4602f3215bb79a625b97e43b

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        targetPort: 80
        port: 10127

workload:
  main:
    podSpec:
      containers:
        main:
          env:
            MAX_UPLOAD: 5000
            PHP_MEMORY_LIMIT: "512M"
            PHP_MAX_FILE_UPLOAD: 200

persistence:
  config:
    enabled: true
    mountPath: "/config"
    size: 2Gi
  projectsend-config:
    enabled: true
    type: configmap
    objectName: projectsend-config
    mountPath: /config/projectsend/sys.config.php
    subPath: sys.config.php
    readOnly: true
  data:helm
    enabled: true
    mountPath: "/data"
    size: 20Gi
  varrun:
    enabled: true

mariadb:
  enabled: true
  mariadbUsername: projectsend
  mariadbDatabase: projectsend

portal:
  open:
    enabled: true
