apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wg-easy
  namespace: argocd
spec:
  destination:
    namespace: default
  project: default
  sources:
    # Chart from Chart Repo
    - chart: wg-easy
      repoURL: https://charts.truecharts.org/
      targetRevision: 5.0.0
      helm:
        # https://argo-cd.readthedocs.io/en/stable/user-guide/multiple_sources/#helm-value-files-from-external-git-repository
        valueFiles:
        - $values/Apps/wg-easy/values.yml
    # Values from Git
    - repoURL: 'https://github.com/Kagiso-me/Kubernetes-k3s/'
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true